steps:
  # Single step to install Git, curl, Poetry, and verify installations
  - id: "Install and Verify"
    name: "python:3.11-slim" # Use the appropriate Python version
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y git curl && \
        pip install --upgrade pip && \
        curl -sSL https://install.python-poetry.org | python3 - && \
        /builder/home/.local/bin/poetry --version && \
        git --version && \
        /builder/home/.local/bin/poetry install     

timeout: '1200s'
