steps:
  # Step 1: Install Git and curl
  - id: "Install Git and curl"
    name: "python:3.11-slim" # Use the appropriate Python version
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y git curl

  # Step 2: Install Poetry
  - id: "Install Poetry"
    name: "python:3.11-slim" # Use the appropriate Python version
    entrypoint: sh
    args:
      - "-c"
      - |
        pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        /builder/home/.local/bin/poetry --version

  # Step 3: Verify Poetry and Git installation
  - id: "Verify Poetry and Git"
    name: "python:3.11-slim"
    entrypoint: sh
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y git curl
        pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        /builder/home/.local/bin/poetry --version
        git --version

timeout: '1200s'
