steps:
  # Step 1: Use an Ubuntu image and install necessary packages including GitHub CLI
  - name: 'ubuntu'
    entrypoint: 'bash'
    secretEnv: ['git_token']
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y curl git gnupg2 && \
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && \
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
        apt-get update && \
        apt-get install -y gh && \
        gh --version
        export git_token=${git_token}
        # Authenticate using the personal access token
        echo $git_token | gh auth login --with-token

        # Use the provided tag name and other environment variables
        TAG_NAME=${TAG_NAME}
        RELEASE_TITLE=${RELEASE_TITLE}
        RELEASE_NOTES=${RELEASE_NOTES}

        echo "Using tag: $TAG_NAME"
        echo "Release title: $RELEASE_TITLE"
        echo "Release notes: $RELEASE_NOTES"

        # Create a new GitHub release
        gh release create $TAG_NAME --title "$RELEASE_TITLE" --notes "$RELEASE_NOTES"

        echo "Release $TAG_NAME created successfully!"
  
substitutions:
  TAG_NAME: 'v4.0.0'
  RELEASE_TITLE: 'Initial Release'
  RELEASE_NOTES: 'Release notes for the initial release.'        


availableSecrets:
  secretManager:
    - versionName: projects/sai-sandbox-20240119/secrets/github_token/versions/latest
      env: 'git_token'

options:
  logging: CLOUD_LOGGING_ONLY
