steps:
  # Step 1: Use an Ubuntu image and install necessary packages including GitHub CLI
  - name: 'ubuntu'
    entrypoint: 'bash'
    secretEnv: ['git_token']
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get install -y curl git gnupg2 && \
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && \
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
        apt-get update && \
        apt-get install -y gh && \
        gh --version
        export git_token=${git_token}

        # Authenticate using the personal access token
        echo $git_token | gh auth login --with-token

        # Create a new GitHub release
        gh release create "${_TAG_NAME}" --title "${_RELEASE_TITLE}" --notes "${_RELEASE_NOTES}"

        echo "Release $_TAG_NAME created successfully!"     

substitutions:
  _TAG_NAME: 'v5.0.1'
  _RELEASE_TITLE: 'Initial Release'
  _RELEASE_NOTES: 'Release notes for the initial release.'

availableSecrets:
  secretManager:
    - versionName: projects/sai-sandbox-20240119/secrets/github_token/versions/latest
      env: 'git_token'

options:
  logging: CLOUD_LOGGING_ONLY
