steps:
  # Step 1: Install the GitHub CLI
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y gh

  # Step 2: Fetch the GitHub token from Secret Manager and create a GitHub release
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the GitHub token from Secret Manager
        GITHUB_TOKEN=$(gcloud secrets versions access latest --secret="github_token" --format="get(payload.data)" | tr '_-' '/+' | base64 -d)
        
        # Authenticate with GitHub CLI using the secret directly from environment variable
        echo $GITHUB_TOKEN | gh auth login --with-token

        # Use the provided tag name and other environment variables
        TAG_NAME=$TAG_NAME
        RELEASE_TITLE=$RELEASE_TITLE
        RELEASE_NOTES=$RELEASE_NOTES

        echo "Using tag: $TAG_NAME"
        echo "Release title: $RELEASE_TITLE"
        echo "Release notes: $RELEASE_NOTES"

        # Create a new GitHub release
        gh release create $TAG_NAME --title "$RELEASE_TITLE" --notes "$RELEASE_NOTES"

        echo "Release $TAG_NAME created successfully!"

substitutions:
  _TAG_NAME: 'v1.0.0'
  _RELEASE_TITLE: 'Initial Release'
  _RELEASE_NOTES: 'Release notes for the initial release.'

secrets:
  - secretEnv:
      GITHUB_TOKEN: github_token
